### ISSUE TITLE
有一些问题和疑问~

### ISSUE THREAD

**Issue by Mateoust** [AMEKENN/miHoYoSign#1]
1.就是连接Mirai之后提示图中的情况。
![QQ截图20210127135515](https://user-images.githubusercontent.com/46558043/105950173-e8b6d300-60a8-11eb-829d-6a4f81551a8a.png)
这是我的setting.yml信息
debug: false
proxy: ''
bots: 
  112233445566: 
    cacheImage: false
    cacheRecord: false
    heartbeat: 
      enable: false
      interval: 1500
    http: 
      enable: true
      host: 0.0.0.0
      port: 4400
      accessToken: ''
      postUrl: ''
      postMessageFormat: string
      secret: ''
    ws_reverse: 
      - enable: true
        postMessageFormat: string
        reverseHost: 127.0.0.1
        reversePort: 4400
        accessToken: ''
        reversePath: /ysbbssign
        reverseApiPath: /api
        reverseEventPath: /event
        useUniversal: true
        useTLS: false
        reconnectInterval: 3000

这是application.yml文件的
server:
  port: 4440
  url: "127.0.0.1:4400"
希望大大能帮我看看

2.就是数据库支持sql lite吗？
3.貌似\src\main\resources\static\里面有一些uid和token的信息
4.在配置看是http发送通知。那么WebSocket是做什么的呢？

先谢过大佬了

**Comment by AMEKENN** [comment]
1.反向代理的端口和服务器端口不一样,所以连接出错reversePort:和server: port要一样
2.没有添加sqllite驱动,所以不支持,只加了mysql,如果学过springboot,可以自己改改
3.感谢提醒,这里面是我自己的账号数据,不过是很久之前的了,这个其实早写完了,一直用的http-post模式所以一个号只能上报给一个地址,自己用没事,发出来可能会影响别人的其他程序运行,而且,http-post对启动顺序有要求,必须先启动签到程序在启动mirai,有点麻烦,所以最近才改
4.websocket是接收mirai推的消息的,签到的通知发消息还是用http,因为签到的通知是定时任务,session管理会有问题(可能只是我菜),mirai如果中间断开连接了,再次连接上会是一个新的session,应该会影响签到后的通知,我就没试,而且http发消息方便

**Comment by Mateoust** [comment]
> 1.反向代理的端口和服务器端口不一样,所以连接出错reversePort:和server: port要一样
> 2.没有添加sqllite驱动,所以不支持,只加了mysql,如果学过springboot,可以自己改改
> 3.感谢提醒,这里面是我自己的账号数据,不过是很久之前的了,这个其实早写完了,一直用的http-post模式所以一个号只能上报给一个地址,自己用没事,发出来可能会影响别人的其他程序运行,而且,http-post对启动顺序有要求,必须先启动签到程序在启动mirai,有点麻烦,所以最近才改
> 4.websocket是接收mirai推的消息的,签到的通知发消息还是用http,因为签到的通知是定时任务,session管理会有问题(可能只是我菜),mirai如果中间断开连接了,再次连接上会是一个新的session,应该会影响签到后的通知,我就没试,而且http发消息方便

了解了，感谢解答
