### ISSUE TITLE
无法接入go-cqhttp

### ISSUE THREAD

**Issue by lemonno2333** [AMEKENN/miHoYoSign#2]
在使用go-cqhttp的时候连接不上反向ws服务，yml文件已经修改好了，mysql也配置完毕，下面是截图
![屏幕截图 2021-01-31 164248](https://user-images.githubusercontent.com/49359040/106378962-9b599f00-63e3-11eb-8fa6-24aec5f1dd41.jpg)
![屏幕截图 2021-01-31 164351](https://user-images.githubusercontent.com/49359040/106378963-9bf23580-63e3-11eb-8181-69f4520d1b07.jpg)

![屏幕截图 2021-01-31 162019](https://user-images.githubusercontent.com/49359040/106378961-998fdb80-63e3-11eb-9537-f29a657b3784.jpg)

**Comment by AMEKENN** [comment]
亲测可以接入go-cqhttp
![B1I7B }PVQEHS{G9531VAPL](https://user-images.githubusercontent.com/40465993/106379641-49674800-63e8-11eb-97cf-7930694a87d6.png)
![NB812B~1RW_BD0OGUN3O_~W](https://user-images.githubusercontent.com/40465993/106379657-70257e80-63e8-11eb-822e-5c2eba9e1eda.png)
可能配置存在问题,给你我刚才测试的配置作为参考
```
    http_config: {
        enabled: true
        host: 0.0.0.0
        port: 4400
        timeout: 0
        post_urls: {}
    }

    ws_reverse_servers: [
        {
            // 是否启用该推送
            enabled: true
            reverse_url: ws://127.0.0.1:4000/ysbbssign
            // 重连间隔 单位毫秒
            reverse_reconnect_interval: 3000
        }
    ]
```

**Comment by lemonno2333** [comment]
加上ws://就好了，谢谢dalao
