### ISSUE TITLE
是不是header过期了

### ISSUE THREAD

**Issue by KimigaiiWuyi** [AMEKENN/miHoYoSign#4]
![78K DJ~_81W_RDGP 1I@VTT](https://user-images.githubusercontent.com/55526518/124362346-d861e000-dc66-11eb-9692-0a71e60f9d51.png)

**Comment by AMEKENN** [comment]
是加了图形验证码，只能直接cookie登录了

**Comment by KimigaiiWuyi** [comment]
> 是加了图形验证码，只能直接cookie登录了

直接cookies登陆怎么搞

**Comment by AMEKENN** [comment]
> 直接cookies登陆怎么搞

得用新的程序，但我没推，才放暑假，等我过两天修修补补好后再推

**Comment by KimigaiiWuyi** [comment]
> > 直接cookies登陆怎么搞
> 
> 得用新的程序，但我没推，才放暑假，等我过两天修修补补好后再推

做好了第一时间踢我一脚 我第一个试用🤗

**Comment by AMEKENN** [comment]
> 做好了第一时间踢我一脚 我第一个试用🤗
好了

**Comment by KimigaiiWuyi** [comment]
> > 做好了第一时间踢我一脚 我第一个试用🤗
> > 好了

![Snipaste_2021-07-12_20-48-30](https://user-images.githubusercontent.com/55526518/125290119-8c8ff480-e352-11eb-8cff-ea7908c00c7c.png)
刚刚装好，不知道是什么原因

**Comment by AMEKENN** [comment]
> 刚刚装好，不知道是什么原因

我返回消息用的是http,所以会不会是url设置的不对,或者cqhttp的http没开

**Comment by KimigaiiWuyi** [comment]
> > 刚刚装好，不知道是什么原因
> 
> 我返回消息用的是http,所以会不会是url设置的不对,或者cqhttp的http没开

刚发现一个低级错误，一边http端口写的4440，一边是4400，现在设置好了，发送完帮助之后，两分钟没有回复，还是设置错了嘛
![Snipaste_2021-07-12_21-58-58](https://user-images.githubusercontent.com/55526518/125300329-7f780300-e35c-11eb-9a99-f50f2fc8dfd6.png)

**Comment by AMEKENN** [comment]
> > > 刚刚装好，不知道是什么原因
> > 
> > 我返回消息用的是http,所以会不会是url设置的不对,或者cqhttp的http没开
> 
> 刚发现一个低级错误，一边http端口写的4440，一边是4400，现在设置好了，发送完帮助之后，两分钟没有回复，还是设置错了嘛
> ![Snipaste_2021-07-12_21-58-58](https://user-images.githubusercontent.com/55526518/125300329-7f780300-e35c-11eb-9a99-f50f2fc8dfd6.png)
> 

这好像是没触发啊，这版本加了自定义关键字，app.yml的commands被修改过？

**Comment by KimigaiiWuyi** [comment]
> > > > 刚刚装好，不知道是什么原因
> > > 
> > > 
> > > 我返回消息用的是http,所以会不会是url设置的不对,或者cqhttp的http没开
> > 
> > 
> > 刚发现一个低级错误，一边http端口写的4440，一边是4400，现在设置好了，发送完帮助之后，两分钟没有回复，还是设置错了嘛
> > ![Snipaste_2021-07-12_21-58-58](https://user-images.githubusercontent.com/55526518/125300329-7f780300-e35c-11eb-9a99-f50f2fc8dfd6.png)
> 
> 这好像是没触发啊，这版本加了自定义关键字，app.yml的commands被修改过？

不，没有动过
![Snipaste_2021-07-12_22-56-42](https://user-images.githubusercontent.com/55526518/125309571-7428d580-e364-11eb-9f1a-e8f9b63cd791.png)

**Comment by KimigaiiWuyi** [comment]
> > > > > 刚刚装好，不知道是什么原因
> > > > 
> > > > 
> > > > 我返回消息用的是http,所以会不会是url设置的不对,或者cqhttp的http没开
> > > 
> > > 
> > > 刚发现一个低级错误，一边http端口写的4440，一边是4400，现在设置好了，发送完帮助之后，两分钟没有回复，还是设置错了嘛
> > > ![Snipaste_2021-07-12_21-58-58](https://user-images.githubusercontent.com/55526518/125300329-7f780300-e35c-11eb-9a99-f50f2fc8dfd6.png)
> > 
> > 
> > 这好像是没触发啊，这版本加了自定义关键字，app.yml的commands被修改过？
> 
> 不，没有动过
> ![Snipaste_2021-07-12_22-56-42](https://user-images.githubusercontent.com/55526518/125309571-7428d580-e364-11eb-9f1a-e8f9b63cd791.png)

大约三分钟后，提示如下
![Snipaste_2021-07-12_22-58-45](https://user-images.githubusercontent.com/55526518/125309967-c10cac00-e364-11eb-9146-fc0c0cbb7d56.png)
这大概也是http的链接问题？

**Comment by AMEKENN** [comment]
> 这大概也是http的链接问题？

是的呢,给cqhttp发消息超时

**Comment by KimigaiiWuyi** [comment]
> > 这大概也是http的链接问题？
> 
> 是的呢,给cqhttp发消息超时

可以帮忙看看您的两边设置是怎么样的吗 难道是设置的问题
可是基本都是上次的配置，上次都能成功发送

**Comment by AMEKENN** [comment]
> 可以帮忙看看您的两边设置是怎么样的吗 难道是设置的问题
> 可是基本都是上次的配置，上次都能成功发送

加QQ好友吗？方便些，而且建议你删了上面几个图片，QQ号暴露了

**Comment by KimigaiiWuyi** [comment]
> > 可以帮忙看看您的两边设置是怎么样的吗 难道是设置的问题
> > 可是基本都是上次的配置，上次都能成功发送
> 
> 加QQ好友吗？方便些，而且建议你删了上面几个图片，QQ号暴露了

可以的，那你直接加就好啦，qq号暴露对我无所谓的~没有暴露其他关键信息就好
